=pod

=encoding utf8

=head1 The RakuPowerTools module

This is the I<README> for the L<PerlPowerTools> Perl module. This
distribution provides pure-Perl6 implementations of popular Unix tools
aimed at the less fortunate systems that don't come with them. This
was inspired by the PerlPowerTools project (http://www.perlpowertools.com)
from Tom Christiansen, who did the same thing with Perl 5.

This is mostly just for giggles now. The PerlPowerTools brought familiar Unix
utilities to Windows, but with the Windows Subsystem for Linux (or Docker, or
whatever), you don't really need this stuff anymore.

=head2 Source location

The source is in GitHub:

=over 4

=item *	L<https://github.com/briandfoy/RakuPowerTools>

=back

If you find a problem, file a ticket in the L<issue
tracker|https://github.com/briandfoy/RakuPowerTools/issues>:

=over 4

=item *	L<https://github.com/briandfoy/RakuPowerTools/issues>

=back

=head2 Getting help

Although I'm happy to hear from module users in private email,
that's the best way for me to forget to do something.

Besides the issue trackers, you can find help at
L<Stackoverflow|http://www.stackoverflow.com>, both of which have many
competent Raku-ers who can answer your question, almost in real time.
They might not know the particulars of this module, but they can help
you diagnose your problem.

=head2 Copyright and License

You should have received a I<LICENSE> file, but the license is also noted
in the module files. About the only thing you can't do is pretend that
you wrote code that you didn't.

=head2 Good luck!

Enjoy,

brian d foy, briandfoy@pobox.com

=cut
